"""Mock painting data for testing label validation."""

# 15 paintings for Text algorithm
TEXT_PAINTINGS = [
    {"id": "text_1", "title": "The Starry Night", "artist": "Vincent van Gogh", "date": "1889", "confidence": 0.95, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/300px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg"},
    {"id": "text_2", "title": "Girl with a Pearl Earring", "artist": "Johannes Vermeer", "date": "1665", "confidence": 0.92, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/300px-1665_Girl_with_a_Pearl_Earring.jpg"},
    {"id": "text_3", "title": "The Birth of Venus", "artist": "Sandro Botticelli", "date": "1485", "confidence": 0.88, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/300px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg"},
    {"id": "text_4", "title": "The Great Wave", "artist": "Katsushika Hokusai", "date": "1831", "confidence": 0.85, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/The_Great_Wave_off_Kanagawa.jpg/300px-The_Great_Wave_off_Kanagawa.jpg"},
    {"id": "text_5", "title": "The Night Watch", "artist": "Rembrandt van Rijn", "date": "1642", "confidence": 0.91, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Night_Watch_-_HD.jpg/300px-The_Night_Watch_-_HD.jpg"},
    {"id": "text_6", "title": "The Kiss", "artist": "Gustav Klimt", "date": "1908", "confidence": 0.87, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Gustav_Klimt_016.jpg/300px-Gustav_Klimt_016.jpg"},
    {"id": "text_7", "title": "Las Meninas", "artist": "Diego Velázquez", "date": "1656", "confidence": 0.84, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Las_Meninas_01.jpg/300px-Las_Meninas_01.jpg"},
    {"id": "text_8", "title": "The Creation of Adam", "artist": "Michelangelo", "date": "1512", "confidence": 0.93, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg/300px-Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg"},
    {"id": "text_9", "title": "American Gothic", "artist": "Grant Wood", "date": "1930", "confidence": 0.86, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg/300px-Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg"},
    {"id": "text_10", "title": "Guernica", "artist": "Pablo Picasso", "date": "1937", "confidence": 0.89, "image_url": "https://upload.wikimedia.org/wikipedia/en/thumb/7/74/PicassoGuernica.jpg/300px-PicassoGuernica.jpg"},
    {"id": "text_11", "title": "The Last Supper", "artist": "Leonardo da Vinci", "date": "1498", "confidence": 0.94, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/%C3%9Altima_Cena_-_Da_Vinci_5.jpg/300px-%C3%9Altima_Cena_-_Da_Vinci_5.jpg"},
    {"id": "text_12", "title": "Water Lilies", "artist": "Claude Monet", "date": "1916", "confidence": 0.82, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/300px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg"},
    {"id": "text_13", "title": "The Son of Man", "artist": "René Magritte", "date": "1964", "confidence": 0.80, "image_url": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Magritte_TheSonOfMan.jpg/220px-Magritte_TheSonOfMan.jpg"},
    {"id": "text_14", "title": "Liberty Leading the People", "artist": "Eugène Delacroix", "date": "1830", "confidence": 0.90, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg/300px-Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg"},
    {"id": "text_15", "title": "The Garden of Earthly Delights", "artist": "Hieronymus Bosch", "date": "1510", "confidence": 0.83, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/The_Garden_of_earthly_delights.jpg/300px-The_Garden_of_earthly_delights.jpg"}
]

# 15 paintings for Multimodal algorithm
MULTIMODAL_PAINTINGS = [
    {"id": "multi_1", "title": "Mona Lisa", "artist": "Leonardo da Vinci", "date": "1503", "confidence": 0.97, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/300px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg"},
    {"id": "multi_2", "title": "The Persistence of Memory", "artist": "Salvador Dalí", "date": "1931", "confidence": 0.94, "image_url": "https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/The_Persistence_of_Memory.jpg/300px-The_Persistence_of_Memory.jpg"},
    {"id": "multi_3", "title": "The Scream", "artist": "Edvard Munch", "date": "1893", "confidence": 0.91, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/300px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg"},
    {"id": "multi_4", "title": "The Kiss", "artist": "Gustav Klimt", "date": "1908", "confidence": 0.89, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Gustav_Klimt_016.jpg/300px-Gustav_Klimt_016.jpg"},
    {"id": "multi_5", "title": "Impression, Sunrise", "artist": "Claude Monet", "date": "1872", "confidence": 0.88, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/300px-Monet_-_Impression%2C_Sunrise.jpg"},
    {"id": "multi_6", "title": "Whistlers Mother", "artist": "James McNeill Whistler", "date": "1871", "confidence": 0.85, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Whistlers_Mother_high_res.jpg/300px-Whistlers_Mother_high_res.jpg"},
    {"id": "multi_7", "title": "The Arnolfini Portrait", "artist": "Jan van Eyck", "date": "1434", "confidence": 0.92, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg/300px-Van_Eyck_-_Arnolfini_Portrait.jpg"},
    {"id": "multi_8", "title": "The School of Athens", "artist": "Raphael", "date": "1511", "confidence": 0.96, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/300px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg"},
    {"id": "multi_9", "title": "A Sunday Afternoon", "artist": "Georges Seurat", "date": "1886", "confidence": 0.84, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/300px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg"},
    {"id": "multi_10", "title": "The Tower of Babel", "artist": "Pieter Bruegel", "date": "1563", "confidence": 0.86, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project_-_edited.jpg/300px-Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project_-_edited.jpg"},
    {"id": "multi_11", "title": "Nighthawks", "artist": "Edward Hopper", "date": "1942", "confidence": 0.90, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Nighthawks_by_Edward_Hopper_1942.jpg/300px-Nighthawks_by_Edward_Hopper_1942.jpg"},
    {"id": "multi_12", "title": "The Hay Wain", "artist": "John Constable", "date": "1821", "confidence": 0.81, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/John_Constable_The_Hay_Wain.jpg/300px-John_Constable_The_Hay_Wain.jpg"},
    {"id": "multi_13", "title": "Saturn Devouring His Son", "artist": "Francisco Goya", "date": "1823", "confidence": 0.87, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/300px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg"},
    {"id": "multi_14", "title": "Cafe Terrace at Night", "artist": "Vincent van Gogh", "date": "1888", "confidence": 0.93, "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Vincent_Willem_van_Gogh_-_Cafe_Terrace_at_Night_%28Yorck%29.jpg/300px-Vincent_Willem_van_Gogh_-_Cafe_Terrace_at_Night_%28Yorck%29.jpg"},
    {"id": "multi_15", "title": "Christina's World", "artist": "Andrew Wyeth", "date": "1948", "confidence": 0.82, "image_url": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Wyeth-ChristinasWorld-1948.jpg/300px-Wyeth-ChristinasWorld-1948.jpg"}
]

# 15 AI-validated paintings
AI_VALIDATED_PAINTINGS = [
    {"id": "ai_val_1", "title": "Guernica", "artist": "Pablo Picasso", "date": "1937", "image_url": "https://upload.wikimedia.org/wikipedia/en/thumb/7/74/PicassoGuernica.jpg/300px-PicassoGuernica.jpg"},
    {"id": "ai_val_2", "title": "The Night Watch", "artist": "Rembrandt van Rijn", "date": "1642", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Night_Watch_-_HD.jpg/300px-The_Night_Watch_-_HD.jpg"},
    {"id": "ai_val_3", "title": "The Last Supper", "artist": "Leonardo da Vinci", "date": "1498", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/%C3%9Altima_Cena_-_Da_Vinci_5.jpg/300px-%C3%9Altima_Cena_-_Da_Vinci_5.jpg"},
    {"id": "ai_val_4", "title": "The Birth of Venus", "artist": "Sandro Botticelli", "date": "1485", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/300px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg"},
    {"id": "ai_val_5", "title": "The Starry Night", "artist": "Vincent van Gogh", "date": "1889", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/300px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg"},
    {"id": "ai_val_6", "title": "Girl with a Pearl Earring", "artist": "Johannes Vermeer", "date": "1665", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/300px-1665_Girl_with_a_Pearl_Earring.jpg"},
    {"id": "ai_val_7", "title": "The Great Wave", "artist": "Katsushika Hokusai", "date": "1831", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/The_Great_Wave_off_Kanagawa.jpg/300px-The_Great_Wave_off_Kanagawa.jpg"},
    {"id": "ai_val_8", "title": "Mona Lisa", "artist": "Leonardo da Vinci", "date": "1503", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/300px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg"},
    {"id": "ai_val_9", "title": "The Scream", "artist": "Edvard Munch", "date": "1893", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/300px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg"},
    {"id": "ai_val_10", "title": "The Kiss", "artist": "Gustav Klimt", "date": "1908", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Gustav_Klimt_016.jpg/300px-Gustav_Klimt_016.jpg"},
    {"id": "ai_val_11", "title": "American Gothic", "artist": "Grant Wood", "date": "1930", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg/300px-Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg"},
    {"id": "ai_val_12", "title": "Water Lilies", "artist": "Claude Monet", "date": "1916", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg/300px-Claude_Monet_-_Water_Lilies_-_1906%2C_Ryerson.jpg"},
    {"id": "ai_val_13", "title": "The Persistence of Memory", "artist": "Salvador Dalí", "date": "1931", "image_url": "https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/The_Persistence_of_Memory.jpg/300px-The_Persistence_of_Memory.jpg"},
    {"id": "ai_val_14", "title": "Liberty Leading the People", "artist": "Eugène Delacroix", "date": "1830", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg/300px-Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg"},
    {"id": "ai_val_15", "title": "The Creation of Adam", "artist": "Michelangelo", "date": "1512", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg/300px-Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg"}
]

# 15 Human validated paintings
HUMAN_VALIDATED_PAINTINGS = [
    {"id": "human_1", "title": "Las Meninas", "artist": "Diego Velázquez", "date": "1656", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Las_Meninas_01.jpg/300px-Las_Meninas_01.jpg"},
    {"id": "human_2", "title": "The Garden of Earthly Delights", "artist": "Hieronymus Bosch", "date": "1510", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/The_Garden_of_earthly_delights.jpg/300px-The_Garden_of_earthly_delights.jpg"},
    {"id": "human_3", "title": "The Arnolfini Portrait", "artist": "Jan van Eyck", "date": "1434", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg/300px-Van_Eyck_-_Arnolfini_Portrait.jpg"},
    {"id": "human_4", "title": "The School of Athens", "artist": "Raphael", "date": "1511", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/300px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg"},
    {"id": "human_5", "title": "Impression, Sunrise", "artist": "Claude Monet", "date": "1872", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/300px-Monet_-_Impression%2C_Sunrise.jpg"},
    {"id": "human_6", "title": "A Sunday Afternoon", "artist": "Georges Seurat", "date": "1886", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/300px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg"},
    {"id": "human_7", "title": "The Tower of Babel", "artist": "Pieter Bruegel", "date": "1563", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project_-_edited.jpg/300px-Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project_-_edited.jpg"},
    {"id": "human_8", "title": "Nighthawks", "artist": "Edward Hopper", "date": "1942", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Nighthawks_by_Edward_Hopper_1942.jpg/300px-Nighthawks_by_Edward_Hopper_1942.jpg"},
    {"id": "human_9", "title": "The Hay Wain", "artist": "John Constable", "date": "1821", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/John_Constable_The_Hay_Wain.jpg/300px-John_Constable_The_Hay_Wain.jpg"},
    {"id": "human_10", "title": "Whistlers Mother", "artist": "James McNeill Whistler", "date": "1871", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Whistlers_Mother_high_res.jpg/300px-Whistlers_Mother_high_res.jpg"},
    {"id": "human_11", "title": "Saturn Devouring His Son", "artist": "Francisco Goya", "date": "1823", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/300px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg"},
    {"id": "human_12", "title": "Cafe Terrace at Night", "artist": "Vincent van Gogh", "date": "1888", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Vincent_Willem_van_Gogh_-_Cafe_Terrace_at_Night_%28Yorck%29.jpg/300px-Vincent_Willem_van_Gogh_-_Cafe_Terrace_at_Night_%28Yorck%29.jpg"},
    {"id": "human_13", "title": "Christina's World", "artist": "Andrew Wyeth", "date": "1948", "image_url": "https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Wyeth-ChristinasWorld-1948.jpg/300px-Wyeth-ChristinasWorld-1948.jpg"},
    {"id": "human_14", "title": "The Hunters in the Snow", "artist": "Pieter Bruegel", "date": "1565", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_%28Winter%29_-_Google_Art_Project.jpg/300px-Pieter_Bruegel_the_Elder_-_Hunters_in_the_Snow_%28Winter%29_-_Google_Art_Project.jpg"},
    {"id": "human_15", "title": "The Fighting Temeraire", "artist": "J.M.W. Turner", "date": "1839", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/The_Fighting_Temeraire%2C_JMW_Turner%2C_National_Gallery.jpg/300px-The_Fighting_Temeraire%2C_JMW_Turner%2C_National_Gallery.jpg"}
]

# 15 Expert validated paintings
EXPERT_VALIDATED_PAINTINGS = [
    {"id": "expert_1", "title": "The Creation of Adam", "artist": "Michelangelo", "date": "1512", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg/300px-Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg"},
    {"id": "expert_2", "title": "Mona Lisa", "artist": "Leonardo da Vinci", "date": "1503", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/300px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg"},
    {"id": "expert_3", "title": "The Last Supper", "artist": "Leonardo da Vinci", "date": "1498", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/%C3%9Altima_Cena_-_Da_Vinci_5.jpg/300px-%C3%9Altima_Cena_-_Da_Vinci_5.jpg"},
    {"id": "expert_4", "title": "The Birth of Venus", "artist": "Sandro Botticelli", "date": "1485", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/300px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg"},
    {"id": "expert_5", "title": "The Night Watch", "artist": "Rembrandt van Rijn", "date": "1642", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Night_Watch_-_HD.jpg/300px-The_Night_Watch_-_HD.jpg"},
    {"id": "expert_6", "title": "Guernica", "artist": "Pablo Picasso", "date": "1937", "image_url": "https://upload.wikimedia.org/wikipedia/en/thumb/7/74/PicassoGuernica.jpg/300px-PicassoGuernica.jpg"},
    {"id": "expert_7", "title": "The Starry Night", "artist": "Vincent van Gogh", "date": "1889", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/300px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg"},
    {"id": "expert_8", "title": "Girl with a Pearl Earring", "artist": "Johannes Vermeer", "date": "1665", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/300px-1665_Girl_with_a_Pearl_Earring.jpg"},
    {"id": "expert_9", "title": "The Kiss", "artist": "Gustav Klimt", "date": "1908", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Gustav_Klimt_016.jpg/300px-Gustav_Klimt_016.jpg"},
    {"id": "expert_10", "title": "The Scream", "artist": "Edvard Munch", "date": "1893", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/300px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg"},
    {"id": "expert_11", "title": "Las Meninas", "artist": "Diego Velázquez", "date": "1656", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Las_Meninas_01.jpg/300px-Las_Meninas_01.jpg"},
    {"id": "expert_12", "title": "The School of Athens", "artist": "Raphael", "date": "1511", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/300px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg"},
    {"id": "expert_13", "title": "American Gothic", "artist": "Grant Wood", "date": "1930", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg/300px-Grant_Wood_-_American_Gothic_-_Google_Art_Project.jpg"},
    {"id": "expert_14", "title": "The Garden of Earthly Delights", "artist": "Hieronymus Bosch", "date": "1510", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/The_Garden_of_earthly_delights.jpg/300px-The_Garden_of_earthly_delights.jpg"},
    {"id": "expert_15", "title": "Liberty Leading the People", "artist": "Eugène Delacroix", "date": "1830", "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg/300px-Eug%C3%A8ne_Delacroix_-_Le_28_Juillet._La_Libert%C3%A9_guidant_le_peuple.jpg"}
]
