"""
Mock thesaurus terms for autocomplete functionality.

Contains ~50 terms per thesaurus for testing the autocomplete search bar.
"""

# Garnier thesaurus - art historical terminology
GARNIER_TERMS = [
    "Portrait",
    "Landscape",
    "Still Life",
    "Religious Scene",
    "Mythological Scene",
    "Genre Scene",
    "History Painting",
    "Battle Scene",
    "Marine Scene",
    "Cityscape",
    "Interior Scene",
    "Nude",
    "Self-Portrait",
    "Group Portrait",
    "Equestrian Portrait",
    "Altarpiece",
    "Triptych",
    "Polyptych",
    "Predella",
    "Fresco",
    "Mural",
    "Ceiling Painting",
    "Panel Painting",
    "Canvas Painting",
    "Miniature",
    "Illuminated Manuscript",
    "Tapestry",
    "Mosaic",
    "Sculpture",
    "Relief",
    "Bust",
    "Statue",
    "Monument",
    "Fountain",
    "Garden Sculpture",
    "Architectural Element",
    "Decorative Arts",
    "Furniture",
    "Ceramics",
    "Glassware",
    "Metalwork",
    "Jewelry",
    "Textile",
    "Print",
    "Etching",
    "Engraving",
    "Lithograph",
    "Woodcut",
    "Drawing",
    "Sketch",
]

# AAT (Getty Art & Architecture Thesaurus) terms
AAT_TERMS = [
    "Abstract Art",
    "Academic Art",
    "Action Painting",
    "Aerial View",
    "Allegory",
    "Anamorphosis",
    "Anthropomorphism",
    "Apocalyptic Scene",
    "Arabesque",
    "Architectural Capriccio",
    "Art Brut",
    "Art Deco",
    "Art Nouveau",
    "Assemblage",
    "Avant-garde",
    "Bamboccianti",
    "Baroque",
    "Bas-relief",
    "Bauhaus",
    "Biedermeier",
    "Body Art",
    "Byzantine",
    "Caricature",
    "Chiaroscuro",
    "Classicism",
    "Collage",
    "Conceptual Art",
    "Constructivism",
    "Cubism",
    "Dada",
    "Divisionism",
    "Expressionism",
    "Fauvism",
    "Figurative Art",
    "Flemish Baroque",
    "Futurism",
    "Genre Painting",
    "Gothic",
    "Grisaille",
    "Grotesque",
    "Haut-relief",
    "Hudson River School",
    "Iconography",
    "Illumination",
    "Impasto",
    "Impressionism",
    "Installation Art",
    "Mannerism",
    "Minimalism",
    "Modernism",
]

# Iconclass - iconographic classification
ICONCLASS_TERMS = [
    "Christian Saints",
    "Virgin Mary",
    "Christ Crucifixion",
    "Christ Nativity",
    "Last Supper",
    "Resurrection",
    "Ascension",
    "Annunciation",
    "Visitation",
    "Pentecost",
    "Adam and Eve",
    "Garden of Eden",
    "Original Sin",
    "Noah's Ark",
    "Tower of Babel",
    "Abraham",
    "Moses",
    "Ten Commandments",
    "David and Goliath",
    "Solomon",
    "Judith and Holofernes",
    "Samson",
    "Daniel in the Lions' Den",
    "Greek Gods",
    "Roman Gods",
    "Zeus",
    "Apollo",
    "Venus",
    "Diana",
    "Mercury",
    "Mars",
    "Hercules",
    "Perseus",
    "Theseus",
    "Prometheus",
    "Pandora",
    "Orpheus",
    "Muses",
    "Graces",
    "Fates",
    "Judgment of Paris",
    "Trojan War",
    "Fall of Troy",
    "Odysseus",
    "Aeneas",
    "Romulus and Remus",
    "Allegory of Time",
    "Vanitas",
    "Memento Mori",
    "Four Seasons",
]

# Fabritius internal label system
FABRITIUS_TERMS = [
    "Belgian Art",
    "Flemish Primitives",
    "Bruegel Family",
    "Rubens Workshop",
    "Van Dyck",
    "Jordaens",
    "Teniers",
    "Dutch Golden Age",
    "Rembrandt School",
    "Vermeer Style",
    "Frans Hals",
    "Italian Renaissance",
    "Florentine School",
    "Venetian School",
    "Roman School",
    "Caravaggio Followers",
    "French Baroque",
    "Spanish Golden Age",
    "Velázquez",
    "Zurbarán",
    "El Greco",
    "German Renaissance",
    "Dürer",
    "Cranach",
    "Holbein",
    "19th Century Belgium",
    "Belgian Symbolism",
    "James Ensor",
    "Félicien Rops",
    "Constantin Meunier",
    "Paul Delvaux",
    "René Magritte",
    "Belgian Surrealism",
    "Les Vingt",
    "Brussels School",
    "Antwerp School",
    "Marine Paintings",
    "Animal Paintings",
    "Flower Still Life",
    "Kitchen Still Life",
    "Vanitas Still Life",
    "Trompe-l'oeil",
    "Peasant Scene",
    "Market Scene",
    "Tavern Scene",
    "Musical Company",
    "Guardroom Scene",
    "Winter Landscape",
    "Forest Scene",
]

# Dictionary mapping thesaurus IDs to their terms
THESAURUS_TERMS = {
    "garnier": GARNIER_TERMS,
    "aat": AAT_TERMS,
    "iconclass": ICONCLASS_TERMS,
    "fabritius": FABRITIUS_TERMS,
}


def get_thesaurus_terms(thesaurus_id: str) -> list[str]:
    """
    Get terms for a specific thesaurus.
    
    Args:
        thesaurus_id: Thesaurus identifier (e.g., "garnier", "aat")
    
    Returns:
        List of term strings for autocomplete
    """
    return THESAURUS_TERMS.get(thesaurus_id.lower(), [])
